### ISSUE TITLE
dora returns "No offer received" when other interfaces are assigned static IP addresses

### ISSUE THREAD

**Issue by soliwilos** [glitchub/dora#1] opened 2022-05-31 15:10 UTC
First off, thank you for a very nice and simple dhcp client.

Running "dora acquire eth0" works only when none of the other network interfaces have an IP address. If either eth1, eth2 or eth3 have a static IP address, dora returns "No offer received" after the default timeout and 4 attempts are over.

Running "ip address del ..." commands for the other network interfaces let's dora do it's thing.

Hoping there is a simple solution.

**Comment by glitchub** [comment] 2022-06-02 18:07
Hi I'm unable to reproduce this, can you start "tcpdump -i eth0 udp port 67 or udp port 68" in another terminal and then try "dora -v eth0 acquire"?

**Comment by soliwilos** [comment] 2022-06-02 19:36
Hello,

If it makes a difference I am using a musl libc system (alpine linux).

Tested with eth0 in UP state, and no IP assigned. I added 192.168.1.1/24 to eth1, and started "tcpdump -i eth0 udp port 67 or udp port 68" which shows packets using the IP on eth1, when I run "dora -v acquire eth0":

`20:52:05.539538 IP 192.168.1.1.68 > 255.255.255.255.67: BOOTP/DHCP, Request from a0:b1:c2:d3:e4:f5 (oui Unknown), length 261

20:52:09.825028 IP 192.168.1.1.68 > 255.255.255.255.67: BOOTP/DHCP, Request from a0:b1:c2:d3:e4:f5 (oui Unknown), length 261

20:52:15.772279 IP 192.168.1.1.68 > 255.255.255.255.67: BOOTP/DHCP, Request from a0:b1:c2:d3:e4:f5 (oui Unknown), length 261

20:52:20.939815 IP 192.168.1.1.68 > 255.255.255.255.67: BOOTP/DHCP, Request from a0:b1:c2:d3:e4:f5 (oui Unknown), length 261`

**Comment by soliwilos** [comment] 2022-06-04 12:20
I may have been mistaken when I initially wrote that "dora renew server eth0" had the same problem as "dora acquire eth0". Just thought I'd update here with the info that "dora renew server eth0" works as intended.

**Comment by soliwilos** [comment] 2022-06-05 11:04
Hi,

I did some more testing on another system and see the same results with tcpdump. Dora for some reason transmits dhcp requests from ethX using whatever IP ethY has, and if ethY does not have any IP, dora uses 0.0.0.0.

It will work if the device running dora reaches a dhcp server on the same network as that IP, but will fail and not get any offers if the dhcp server is on a different network.

The dhcp server I was trying to reach in my initial testing belongs to my ISP and is not on the local network. Dora then only works if it's using 0.0.0.0 in it's dhcp requests, which it doesn't do when another network interface has an IP.

**Comment by soliwilos** [comment] 2022-06-06 12:06
I have tested udhcpc and used tcpdump to see that it's packets use a 0.0.0.0 address, even when another interface has an IP. Confirming that udhcpc does not have this issue.

In this example the dhcp packets being sent to the server use 192.168.1.200
```
ip link set dev eth0 up
ip address add 192.168.1.200/24 dev eth1
dora acquire eth0
```

While in this example the dhcp packets being sent to the server use 0.0.0.0
```
ip link set dev eth0 up
ip address add 192.168.1.200/24 dev eth1
udhcpc -f -i eth0
```

I can only assume that this is the reason for my trouble with dora.

**Comment by glitchub** [comment] 2022-06-07 18:48
Thanks, FYI I did reproduce, the UDP stack is doing this. Not sure if relatively recent kernel behavior or I just didn't notice (my original use case was SBC with only one interface). Probably the fix is to use raw IP for discovery, slowly working on it. 

-v generates a *lot* of output to stderr, your shell is hiding it? (Maybe add "2>&1" on the end?) The "ciaddr=0.0.0.0 yiaddr=0.0.0.0 siaddr=0.0.0.0" should also go to stderr but is printf'd instead, that's a bug.

**Comment by glitchub** [comment] 2022-06-13 23:35
Hello I made a change to use raw packets when the interface is unconfigured, very lightly tested but looks promising. Currently checked into branch 'test', give it a try.

**Comment by soliwilos** [comment] 2022-06-14 12:02
Hi, thank you very much for working on this. Promising indeed, it is working nicely so far. I'll continue testing it.

**Comment by glitchub** [comment] 2022-06-21 01:28
Now uses raw sockets for all transactions by default, which has the benefit of working even if someone is already listening on BOOTPC. Merged to master and the test branch is deleted.

**Closed by glitchub** 2022-06-21 01:28 UTC
